# 不默认模型，都从平台配置
# model_list:
#   - model_name: gpt-4o
#     litellm_params:
#       model: openai/gpt-4o
#       api_key: os.environ/ANTHROPIC_API_KEY

#   - model_name: gpt-4-turbo
#     litellm_params:
#       model: openai/gpt-4-turbo
#       api_key: os.environ/ANTHROPIC_API_KEY

# 更多模型配置...

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: os.environ/DATABASE_URL
  # 生产最佳实践
  proxy_batch_write_at: 60
  database_connection_pool_limit: 20
  # 如需使用 Redis, 请取消以下注释
  # use_redis_transaction_buffer: true

litellm_settings:
  # 生产最佳实践
  set_verbose: false
  request_timeout: 600
  # 如需使用 Redis 缓存, 请取消以下注释
  # cache:
  #   type: "redis"
  #   host: os.environ/REDIS_HOST
  #   port: os.environ/REDIS_PORT
  #   password: os.environ/REDIS_PASSWORD